### ISSUE TITLE
能否支持mvvm上对fscript的调用

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-web#12]
awtk-mvvm, demo28，发现很多功能到了web上就无法执行，提示找不到对应函数
![image](https://github.com/zlgopen/awtk-web/assets/54085641/119843e3-e757-4ee9-be55-2ffe36bc541e)

**Comment by xianjimli** [comment]
加了，你更新awtk试试，谢谢。

**Comment by Tracker647** [comment]
OK，可以了。
