### ISSUE TITLE
支持awtk的按键事件到浏览器上吗

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-web#13]
发现无论传统开发还是mvvm的按键事件，对应按键桌面端正常运行，但到了浏览器上都无响应，后面有支持这部分移植的计划吗？

**Comment by xianjimli** [comment]
好的，谢谢，我先看看。

**Comment by xianjimli** [comment]
你更新awtk-web试试，谢谢

**Comment by Tracker647** [comment]
mvvm demo9 能检测到长按 但是f3 f4点下去没响应。
![image](https://github.com/zlgopen/awtk-web/assets/54085641/bb62f668-469f-4bac-be04-64fed72902f9)

**Comment by Tracker647** [comment]
demo9正常了。
还有一个demo14，没法正常相应，它设置的是key_down属性，目前更新只做了global_key_down的部分吗？

**Comment by xianjimli** [comment]
改了，你更新awtk-web试试，谢谢

**Comment by Tracker647** [comment]
都解决了，谢谢。
