### ISSUE TITLE
字体偏大偏上问题

### ISSUE THREAD

**Issue by Tracker647** [zlgopen/awtk-web#16]
例子ui：
[design.zip](https://github.com/user-attachments/files/16082216/design.zip)

build.json:
```
{
    "name": "menucase",
    "version": "1.0",
    "assets": "res/assets",
    "author": "AWTK Develop Team",
    "copyright": "Guangzhou ZHIYUAN Electronics Co.,Ltd.",
    "themes":["default"],
    "web": {
      "app_type": "c",
      "assets": "design",
      "sources": [
        "src/*.c",
        "src/*/*.c"
      ],
      "config": {
        "width": 800,
        "height": 480,
        "fontScale": "0.8",
        "defaultFont": "Inter,sans-serif"
      }
    }
  }
  
```

桌面端效果：
![image](https://github.com/zlgopen/awtk-web/assets/54085641/030b2305-3fc4-43b1-8a61-eb271f41121b)

web端效果：
![image](https://github.com/zlgopen/awtk-web/assets/54085641/edebcb6d-b57a-41b8-8c8a-008405a0449f)

字体大小已经发现可以在awtk_web.js里改：
```
  TBrowser.config.width = TBrowser.getParam('width', TBrowser.config.width);
  TBrowser.config.height = TBrowser.getParam('height', TBrowser.config.height);
  TBrowser.config.nowebgl = TBrowser.getParam('nowebgl', TBrowser.config.nowebgl);
  TBrowser.config.fontScale = 0.8;
  TBrowser.config.defaultFont = "Inter,sans-serif"
```
主要是偏上问题，不知道对齐的js代码在哪，

**Comment by Tracker647** [comment]
好的，这个有效果，offset设成2就差不多了。
不过还是想问问，缺省情况下没法保持原本的对齐状态吗？
另外就是发现同样都是awtk默认的思源黑体字体，web上的英文字体间距比桌面端的还近，所以显示风格看着还是不太一样，不知道为什么。
![image](https://github.com/zlgopen/awtk-web/assets/54085641/fc667468-7a6c-4114-b6bd-4896138d6027)

**Comment by xianjimli** [comment]
> 缺省情况下没法保持原本的对齐状态吗？
对齐不同吗？

**Comment by Tracker647** [comment]
> > 缺省情况下没法保持原本的对齐状态吗？
> > 对齐不同吗？

对的，就是不设offset的时候。

**Comment by xianjimli** [comment]
两个的渲染方式不同，可能有些差异。
