### ISSUE TITLE
编译demoui出现文件缺失错误

### ISSUE THREAD

**Issue by duduathz** [zlgopen/awtk-web#4]
一、
git clone https://github.com/emscripten-core/emsdk.git

cd emsdk

./emsdk install latest

./emsdk activate latest

source ./emsdk_env.sh
安装完成。
二、
编译 awtk 本身

git clone https://github.com/zlgopen/awtk.git
cd awtk
scons -j 8
编译完成。

三、
编译 demoui

git clone https://github.com/zlgopen/awtk-web.git
cd awtk-web
python build.py ../awtk/demos/demoui_build.json all

第三步出现以下错误：
shared:INFO: (Emscripten: Running sanity checks)
**emcc: error: /home/du/AWTK_GUI/awtk-web/webroot/demoui/assets_web.c: No such file or directory ("/home/du/AWTK_GUI/awtk-web/webroot/demoui/assets_web.c" was expected to be an input file, based on the commandline arguments provided)**
gen/app.js
/home/du/AWTK_GUI/awtk-web/webroot/demoui/js/awtk_web.js
/home/du/AWTK_GUI/awtk-web/webroot/demoui/assets_web.js
Traceback (most recent call last):
  File "build.py", line 298, in <module>
    build_awtk_web_js(config)
  File "build.py", line 148, in build_awtk_web_js
    merge_files(awtk_web_js_files, outfile)
  File "build.py", line 46, in merge_files
    with open(fname) as infile:
IOError: [Errno 2] **No such file or directory: u'/home/du/AWTK_GUI/awtk-web/webroot/demoui/assets_web.js'**
请问是否源文件存在错误？
谢谢！

**Comment by xianjimli** [comment]
记得有个版本是有问题，awtk用master最新的代码试试。

**Comment by duduathz** [comment]
谢谢，是pillow安装问题。已解决。
